### ISSUE TITLE
Fails if more than 16 partitions are created

### ISSUE THREAD

**Issue by tdawson** [jsafrane/kubernetes-nfs-pvs#1]
Parted can create up to 128 partitions on a GPT disk, but in RHEL 7, only 16 can be seen.
https://bugzilla.redhat.com/show_bug.cgi?id=1232471
I don't expect you to fix this bug, but it would be great if it were caught early on and exited sanely.
Right now it isn't caught until ansible tries to mount the partitions.  By that time there are several things already setup that you have to clean up to get your disk/machine back to normal.

**Comment by jsafrane** [comment]
I updated the bug, there is something wrong in Kernel or QEMU, it can'd handle VirtIO disks with more than 15 partitions. The script works well with SCSI disks.
